version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ZOOM_ACCOUNT_ID=${ZOOM_ACCOUNT_ID}
      - ZOOM_CLIENT_ID=${ZOOM_CLIENT_ID}
      - ZOOM_CLIENT_SECRET=${ZOOM_CLIENT_SECRET}
      - ZOOM_VERIFICATION_TOKEN=${ZOOM_VERIFICATION_TOKEN}
    command: uvicorn zoom_integration:app --host 0.0.0.0 --port 8000 --reload
